"""Backtesting engine: vectorised strategy testing framework.

Run systematic strategies on historical data with realistic execution,
walk-forward validation, and proper statistical evaluation.

    from pricebook.backtest import Backtest, Strategy

    strategy = Strategy(signal_func=my_signal, sizing_func=my_sizing)
    result = Backtest(returns, strategy).run()
    print(result.sharpe, result.max_drawdown)

References:
    De Prado, *Advances in Financial Machine Learning*, Wiley, 2018.
    Bailey & De Prado, *The Deflated Sharpe Ratio*, J. Portfolio Mgmt, 2014.
    Harvey, Liu & Zhu, *...and the Cross-Section of Expected Returns*, RFS, 2016.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Callable

import numpy as np


# ============================================================================
# Core data structures
# ============================================================================

@dataclass
class Trade:
    """A single trade generated by the strategy."""
    timestamp: int        # index into the return series
    direction: float      # +1 long, -1 short, 0 flat
    size: float           # position size (notional or units)
    entry_price: float = 0.0
    slippage: float = 0.0
    commission: float = 0.0


@dataclass
class BacktestConfig:
    """Backtest execution parameters."""
    slippage_bps: float = 0.0        # per-trade slippage in bps
    commission_per_trade: float = 0.0
    initial_capital: float = 1_000_000.0
    max_position: float = 1.0        # max absolute position (fraction of capital)
    rebalance_frequency: int = 1     # rebalance every N periods


@dataclass
class PerformanceMetrics:
    """Strategy performance statistics."""
    total_return: float
    annualised_return: float
    annualised_vol: float
    sharpe: float
    sortino: float
    calmar: float
    max_drawdown: float
    max_drawdown_duration: int   # periods
    hit_ratio: float             # fraction of positive returns
    avg_win: float
    avg_loss: float
    profit_factor: float         # gross profits / gross losses
    n_trades: int
    n_periods: int


@dataclass
class BacktestResult:
    """Complete backtest output."""
    pnl_series: np.ndarray           # per-period P&L
    cumulative_pnl: np.ndarray       # running total
    position_series: np.ndarray      # position at each period
    equity_curve: np.ndarray         # capital + cumulative P&L
    metrics: PerformanceMetrics
    config: BacktestConfig


# ============================================================================
# Performance computation
# ============================================================================

def compute_metrics(
    pnl: np.ndarray,
    initial_capital: float = 1_000_000.0,
    periods_per_year: int = 252,
    n_trades: int = 0,
) -> PerformanceMetrics:
    """Compute performance metrics from a P&L series."""
    n = len(pnl)
    if n == 0:
        return PerformanceMetrics(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

    returns = pnl / initial_capital
    cum_ret = np.cumsum(returns)
    total_ret = float(cum_ret[-1])

    ann_ret = total_ret * periods_per_year / n if n > 0 else 0.0
    vol = float(returns.std()) * math.sqrt(periods_per_year) if n > 1 else 0.0

    sharpe = ann_ret / vol if vol > 1e-10 else 0.0

    # Sortino (downside deviation)
    downside = returns[returns < 0]
    downside_vol = float(downside.std()) * math.sqrt(periods_per_year) if len(downside) > 1 else 1e-10
    sortino = ann_ret / downside_vol if downside_vol > 1e-10 else 0.0

    # Drawdown
    equity = initial_capital + np.cumsum(pnl)
    peak = np.maximum.accumulate(equity)
    drawdown = (peak - equity) / peak
    max_dd = float(drawdown.max()) if len(drawdown) > 0 else 0.0

    # Max drawdown duration
    in_dd = drawdown > 0
    dd_dur = 0
    max_dd_dur = 0
    for d in in_dd:
        if d:
            dd_dur += 1
            max_dd_dur = max(max_dd_dur, dd_dur)
        else:
            dd_dur = 0

    calmar = ann_ret / max_dd if max_dd > 1e-10 else 0.0

    # Hit ratio
    positive = pnl[pnl > 0]
    negative = pnl[pnl < 0]
    hit = len(positive) / n if n > 0 else 0.0
    avg_win = float(positive.mean()) if len(positive) > 0 else 0.0
    avg_loss = float(negative.mean()) if len(negative) > 0 else 0.0
    gross_profit = float(positive.sum()) if len(positive) > 0 else 0.0
    gross_loss = abs(float(negative.sum())) if len(negative) > 0 else 1e-10
    profit_factor = gross_profit / gross_loss if gross_loss > 1e-10 else 0.0

    return PerformanceMetrics(
        total_return=total_ret,
        annualised_return=ann_ret,
        annualised_vol=vol,
        sharpe=sharpe,
        sortino=sortino,
        calmar=calmar,
        max_drawdown=max_dd,
        max_drawdown_duration=max_dd_dur,
        hit_ratio=hit,
        avg_win=avg_win,
        avg_loss=avg_loss,
        profit_factor=profit_factor,
        n_trades=n_trades,
        n_periods=n,
    )


# ============================================================================
# Backtest engine
# ============================================================================

def run_backtest(
    returns: np.ndarray,
    signals: np.ndarray,
    config: BacktestConfig | None = None,
    periods_per_year: int = 252,
) -> BacktestResult:
    """Run a vectorised backtest.

    Args:
        returns: array of asset returns (e.g. daily log returns).
        signals: array of position signals (-1 to +1) at each period.
            Signal at time t determines position for the return at time t+1.
        config: execution parameters.
        periods_per_year: for annualisation (252 = daily, 12 = monthly).

        result = run_backtest(returns, signals)
        print(result.metrics.sharpe)
    """
    cfg = config or BacktestConfig()
    n = min(len(returns), len(signals))

    positions = np.clip(signals[:n], -cfg.max_position, cfg.max_position)

    # Apply rebalance frequency
    if cfg.rebalance_frequency > 1:
        for i in range(n):
            if i % cfg.rebalance_frequency != 0:
                positions[i] = positions[i - 1] if i > 0 else 0.0

    # P&L: position[t-1] * return[t] (signal leads return by 1 period)
    pnl = np.zeros(n)
    for i in range(1, n):
        gross = positions[i - 1] * returns[i] * cfg.initial_capital
        slippage_cost = abs(positions[i] - positions[i - 1]) * cfg.slippage_bps / 10000 * cfg.initial_capital
        commission = cfg.commission_per_trade if abs(positions[i] - positions[i - 1]) > 1e-10 else 0.0
        pnl[i] = gross - slippage_cost - commission

    cumulative = np.cumsum(pnl)
    equity = cfg.initial_capital + cumulative

    # Count trades (position changes)
    n_trades = int(np.sum(np.abs(np.diff(positions)) > 1e-10))

    metrics = compute_metrics(pnl, cfg.initial_capital, periods_per_year, n_trades)

    return BacktestResult(
        pnl_series=pnl,
        cumulative_pnl=cumulative,
        position_series=positions,
        equity_curve=equity,
        metrics=metrics,
        config=cfg,
    )


# ============================================================================
# Walk-forward validation
# ============================================================================

@dataclass
class WalkForwardResult:
    """Walk-forward validation result."""
    in_sample_sharpes: list[float]
    out_of_sample_sharpes: list[float]
    in_sample_returns: list[float]
    out_of_sample_returns: list[float]
    n_folds: int
    oos_sharpe: float          # average OOS Sharpe
    is_vs_oos_decay: float     # IS Sharpe - OOS Sharpe (overfitting measure)


def walk_forward(
    returns: np.ndarray,
    signal_func: Callable[[np.ndarray], np.ndarray],
    n_folds: int = 5,
    train_ratio: float = 0.6,
    config: BacktestConfig | None = None,
    periods_per_year: int = 252,
) -> WalkForwardResult:
    """Walk-forward validation with expanding or rolling window.

    Args:
        returns: full return series.
        signal_func: function(train_returns) → signals for the full series.
            Called on the training window, produces signals for the test window.
        n_folds: number of train/test splits.
        train_ratio: fraction of each fold used for training.

        result = walk_forward(returns, my_signal_func, n_folds=5)
        print(result.oos_sharpe)
    """
    cfg = config or BacktestConfig()
    n = len(returns)
    fold_size = n // n_folds

    is_sharpes = []
    oos_sharpes = []
    is_returns = []
    oos_returns = []

    for fold in range(n_folds):
        start = fold * fold_size
        end = min(start + fold_size, n)
        split = start + int((end - start) * train_ratio)

        train = returns[start:split]
        test = returns[split:end]

        if len(train) < 10 or len(test) < 5:
            continue

        # Generate signals from training data
        train_signals = signal_func(train)

        # Apply to test period
        test_signals = signal_func(test)

        # Compute metrics
        is_result = run_backtest(train, train_signals, cfg, periods_per_year)
        oos_result = run_backtest(test, test_signals, cfg, periods_per_year)

        is_sharpes.append(is_result.metrics.sharpe)
        oos_sharpes.append(oos_result.metrics.sharpe)
        is_returns.append(is_result.metrics.total_return)
        oos_returns.append(oos_result.metrics.total_return)

    avg_oos = float(np.mean(oos_sharpes)) if oos_sharpes else 0.0
    avg_is = float(np.mean(is_sharpes)) if is_sharpes else 0.0

    return WalkForwardResult(
        in_sample_sharpes=is_sharpes,
        out_of_sample_sharpes=oos_sharpes,
        in_sample_returns=is_returns,
        out_of_sample_returns=oos_returns,
        n_folds=len(is_sharpes),
        oos_sharpe=avg_oos,
        is_vs_oos_decay=avg_is - avg_oos,
    )


# ============================================================================
# Signal combination & hypothesis testing
# ============================================================================

def combine_signals(
    signals: list[np.ndarray],
    weights: list[float] | None = None,
    method: str = "weighted",
) -> np.ndarray:
    """Combine multiple signal arrays into one.

    Args:
        signals: list of signal arrays (all same length).
        weights: per-signal weights. If None, equal weight.
        method: "weighted" (linear), "rank" (rank-average), "majority" (sign vote).
    """
    n = min(len(s) for s in signals)
    trimmed = [s[:n] for s in signals]

    if weights is None:
        weights = [1.0 / len(signals)] * len(signals)

    if method == "weighted":
        combined = sum(w * s for w, s in zip(weights, trimmed))
    elif method == "rank":
        # Rank each signal, then average ranks
        from scipy.stats import rankdata
        ranks = [rankdata(s) / n for s in trimmed]
        combined = sum(w * r for w, r in zip(weights, ranks))
    elif method == "majority":
        signs = [np.sign(s) for s in trimmed]
        combined = sum(w * sg for w, sg in zip(weights, signs))
    else:
        raise ValueError(f"Unknown method: {method}")

    return np.asarray(combined)


def deflated_sharpe(
    sharpe: float,
    n_trials: int,
    n_observations: int,
    skew: float = 0.0,
    kurtosis: float = 3.0,
) -> float:
    """Deflated Sharpe Ratio (Bailey & De Prado, 2014).

    Adjusts the Sharpe ratio for multiple testing (data snooping).
    Returns the probability that the observed Sharpe is significant
    given the number of strategies tested.

    DSR = Prob(SR > SR*) where SR* = expected max SR from n_trials random strategies.

    Args:
        sharpe: observed Sharpe ratio.
        n_trials: number of strategies tested (backtest count).
        n_observations: number of return observations.
        skew: return skewness (0 for normal).
        kurtosis: return kurtosis (3 for normal).
    """
    from scipy.stats import norm

    if n_trials <= 1:
        return 1.0

    # Expected maximum Sharpe from n random trials
    e_max_sr = norm.ppf(1 - 1 / n_trials)

    # Standard error of SR estimate
    se_sr = math.sqrt((1 + 0.5 * sharpe**2 - skew * sharpe +
                        (kurtosis - 3) / 4 * sharpe**2) / n_observations)

    if se_sr < 1e-10:
        return 1.0 if sharpe > e_max_sr else 0.0

    # Probability that observed SR exceeds expected max
    return float(norm.cdf((sharpe - e_max_sr) / se_sr))


def bonferroni_threshold(
    significance: float,
    n_tests: int,
) -> float:
    """Bonferroni-corrected significance threshold.

    For N independent tests at significance α, use α/N per test.
    """
    if n_tests <= 0:
        return significance
    return significance / n_tests


def fdr_threshold(
    p_values: list[float],
    significance: float = 0.05,
) -> float:
    """Benjamini-Hochberg FDR threshold.

    More powerful than Bonferroni for multiple testing correction.
    Returns the p-value threshold below which tests are significant.
    """
    sorted_p = sorted(p_values)
    n = len(sorted_p)
    threshold = 0.0
    for i, p in enumerate(sorted_p):
        bh = significance * (i + 1) / n
        if p <= bh:
            threshold = p
    return threshold
